# Basic mediawiki-node-services config, running the following services in a
# single process:
#
# - RESTBase

services:
  - name: restbase
    module: hyperswitch
    app_base_path: ./node_modules/restbase
    conf:
      port: 7231
      salt: secret
      default_page_size: 125
      user_agent: RESTBase
      ui_name: RESTBase
      ui_url: https://www.mediawiki.org/wiki/RESTBase
      ui_title: RESTBase docs
      spec:
        x-request-filters:
          - path: lib/security_response_header_filter.js
          - path: lib/normalize_headers_filter.js
        x-sub-request-filters:
          - type: default
            name: http
            options:
              allow:
                - pattern: '{env(MEDIAWIKI_API_URL,http://localhost/w/api.php)}'
                  forward_headers: true
                - pattern: http://localhost:8142
                  forward_headers: true
                - pattern: http://localhost:10042
                  forward_headers: true
                - pattern: /^https?:\/\//
        paths:
          /{domain:localhost}:
            x-modules:
              - path: ../../MR.yaml
                options: &default_options
                  action:
                    # XXX Check API URL!
                    apiUriTemplate: '{env(MEDIAWIKI_API_URL,http://localhost/w/api.php)}'
                    baseUriTemplate: "{{'http://{domain}:7231/{domain}/v1'}}"
                  parsoid:
                    # XXX Check Parsoid URL!
                    host: '{env(MEDIAWIKI_REST_URL,http://localhost/w/rest.php)}'
                  table:
                    backend: sqlite
                    dbname: /data/restbase_tables.sqlite3
                    pool_idle_timeout: 20000
                    retry_delay: 250
                    retry_limit: 10
                    show_sql: false
                    storage_groups:
                      - name: local
                        domains: /./
                  mathoid:
                    host: '{env(MATHOID_HOST_PORT,http://localhost:10042)}'
                  mobileapps:
                    host: '{env(MOBILEAPPS_URI,http://localhost:8888)}'
                  citoid:
                    host: '{env(CITOID_URI,http://localhost:1970)}'
                  purged_cache_control: s-maxage=864000, max-age=86400
  - name: mathoid
    # a relative path or the name of an npm package, if different from name
    module: ./mathoid/app.js
    # optionally, a version constraint of the npm package
    # version: ^0.4.0
    # per-service config
    conf:
      port: 10042
      # interface: localhost # uncomment to only listen on localhost
      # more per-service config settings
      svg: true
      img: true
      png: true
      texvcinfo: true
      speech: true
      speech_on: false
      speech_config:
        semantics: true
        domain: 'mathspeak'
        style: 'default'
        semantic: false
        minSTree: false
        speakText: true
        enrich: false
      chem: true
      dpi: 180
      no_check: true
      mj_config:
        extensions: "TeX/color,TeX/mediawiki-texvc,TeX/mhchem"
        MathJax:
          menuSettings:
            semantics: true
          SVG:
            font: "TeX"
          TeX:
            noErrors:
              disabled: true
      svgo: false
      # the location of the spec, defaults to spec.yaml if not specified
      # spec: ./spec.template.yaml
      # allow cross-domain requests to the API (default '*')
      cors: '*'
      # to disable use:
      # cors: false
      # to restrict to a particular domain, use:
      # cors: restricted.domain.org
      # content for the CSP headers
      # csp: false  # uncomment this line to disable sending them

# Finally, a standard service-runner config.
info:
  name: mediawiki-node-services

logging:
  level: info

num_workers: 1
